# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  def get_api_key
    app_store_connect_api_key(
      key_id: "48QQ963XCP",
      issuer_id: "a5dbdb8d-3a08-416a-b308-d5aefac9b57a",
      key_filepath: "./fastlane/AuthKey_48QQ963XCP.p8"
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = get_api_key
    
    version = flutter_version()

    increment_version_number(version_number: version["version_name"], xcodeproj: "Runner.xcodeproj")
    increment_build_number(build_number: version["version_code"], xcodeproj: "Runner.xcodeproj")

    match(
      type: "appstore", 
      api_key: api_key,
      app_identifier: [
        "cirkles.app",
        "cirkles.app.Notification-Service-Extension",
        "cirkles.app.Cirkles-Share-Extension"
      ]
    )
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")

    upload_to_testflight
  end

  desc "Deploy new version to the App Store"
  lane :release do
    api_key = get_api_key
    
    version = flutter_version()

    increment_version_number(version_number: version["version_name"], xcodeproj: "Runner.xcodeproj")
    increment_build_number(build_number: version["version_code"], xcodeproj: "Runner.xcodeproj")
    
    match(
      type: "appstore", 
      api_key: api_key,
      app_identifier: [
        "cirkles.app",
        "cirkles.app.Notification-Service-Extension",
        "cirkles.app.Cirkles-Share-Extension"
      ]
    )
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    
    upload_to_app_store(
      api_key: api_key,
      force: true,
      submit_for_review: false,
      skip_metadata: true,
      skip_screenshots: true,
      run_precheck_before_submit: false
    )
  end
end
